const mongoose = require("mongoose");

const foodSchema = new mongoose.Schema(
    {
        title:{
            type:String,
            required:true,
        },
        image:{
            type:String,
            required:true
        },
        ingredientsInTheRepice:[
            {
                fullDescription:{
                    type:String,
                    required:true
                },
                ingredients:{
                    name:{
                        type:String,
                        required:true
                    },
                    image:{
                        type:String,
                        required:true,
                    }
                },
                measure:{
                    amount:{
                        type:String,
                        required:true
                    },
                    unitOfMeasure:{
                        type:String,
                        required:true,
                    }
                }
            }
        ],
        materials:[
            {
                material:{
                    name:{
                        type:String,
                    },
                    image:{
                        type:String,
                    }
                }
            }
        ],
        description:{
            type:String,
            required:true
        },
        preparationTime:{
            type:Number,
            required:true
        },
        calories:{
            type:Number,
            required:true
        },
        protein:{
            type:Number,
            required:true
        },
        fat:{
            type:Number,
            required:true
        },
        carb:{
            type:Number,
            required:true
        },
        vegan:{
            type:Boolean,
            required:true
        },
        vegetarian:{
            type:Boolean,
            required:true
        },
        glutenFree:{
            type:Boolean,
            required:true
        },
        ketogenic:{
            type:Boolean,
            required:true
        },
        vitamins:[
            {
                vitamin:{
                    name:{
                        type:String,
                    },
                    description:{
                        type:String,
                    }
                }
            }
        ]
    },
    { timestamps: true }
    );

module.exports = mongoose.model("food",foodSchema)